version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run : git clone https://github.com/gwerobe/ex2-backend.git
      - run : ls -al
      - run : cd ex2-backend/
      - run : ls -al 
      - run : npm install
      - run : npm run test

workflows:
  build:
    jobs:
      - checkoutEtTests