version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run : git clone https://github.com/gwerobe/ex2-backend.git
      - node/install
      - run : cd ex2-backend/ && npm install
      - run : cd ex2-backend/ && npm run test
  integrationFrontend:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - run : git clone https://github.com/gwerobe/ex2-backend.git
      - run : git clone https://github.com/gwerobe/ex2-frontend.git
      - node/install
      - run : cd ex2-frontend/ && npm install
      - run : cd ex2-frontend/ && npm run build
      - run : cd ex2-backend/ && mkdir public
      - run : cp -r ex2-frontend/build ex2-frontend/public
      - persist_to_workspace:
          root: .
          paths:
            - Exercice2

workflows:
  build:
    jobs:
      - checkoutEtTests
      - integrationFrontend : 
          requires :
            - checkoutEtTests